version: "3"
services:
  web:
    image: andreipoe/firefox-send
    build:
      context: .
      args:
          - version=v2.5.4
    links:
      - redis
    ports:
      - "127.0.0.1:11443:1443"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    restart: unless-stopped
  redis:
    image: redis:alpine
    restart: unless-stopped
